apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment 
  labels: 
    app: suhas-app 

spec:
    replicas: 4
    selector:
      matchLabels:
         app: suhas-app

    template:
      metadata: 
        name: suhas-pod 
        labels:
          app: suhas-app
      spec:
        containers:
         - name: suhas-container 
           image: nginx:latest 
           ports: 
            - containerPort: 80
           
          
       
